version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: my-demo-db
      POSTGRES_USER: my-db-username
      POSTGRES_PASSWORD: my-db-password
    ports:
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
    - 8091:8080